'''You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.'''

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        char_counts = collections.Counter(t)
        char_count= collections.Counter(s)  
        for char in t:
            if char not in s and char_counts[char] == 1: 
                return char
            elif char_counts[char]>char_count[char]:
                return char
        return None